version: "2"
run:
  allow-parallel-runners: true
  allow-serial-runners: true
output:
  formats:
    text:
      path: stderr
      print-linter-name: true
      print-issued-lines: true
  sort-order:
    - linter
    - severity
    - file
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - err113
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - fatcontext
    - forcetypeassert
    - funlen
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godox
    - goheader
    - gomoddirectives
    - gomodguard_v2
    - goprintffuncname
    - gosec
    - gosmopolitan
    - govet
    - grouper
    - importas
    - inamedparam
    - ineffassign
    - interfacebloat
    - intrange
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - perfsprint
    - prealloc
    - predeclared
    - protogetter
    - reassign
    - sloglint
    - spancheck
    - staticcheck
    - tagalign
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
    - wsl_v5
  exclusions:
    generated: lax
    rules:
      - linters:
          - dupl
          - err113
          - errcheck
          - gocyclo
          - gosec
          - funlen
          - goconst
        path: _test\.go
      - linters:
          - gochecknoinits
        path: cmd/
      - linters:
          - errcheck
        text: .Close
      - linters:
          - varnamelen
        text: variable name 'ok' is too short for the scope of its usage
      - linters:
          - staticcheck
        text: 'ST1000: at least one file in a package should have a package comment'
    paths:
      - third_party$
      - builtin$
      - examples$
      - legacy
issues:
  whole-files: true
  fix: true
severity:
  default: error
formatters:
  settings:
    gci:
      sections:
        - standard
        - default
  enable:
    - gofumpt
    - gci
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
