# yaml-language-server: $schema=https://goreleaser.com/static/schema.json


version: 2

builds:
  - main: ./...
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - arm64
      - amd64
      - "386"

archives:
  - formats: [ tar.gz ]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [ zip ]

changelog:
  disable: true

release:

#
#dockers_v2:
#  - id: xdebug-web-alpine
#    images:
#      - 'thumbrise/xdebug-web'
#    dockerfile: publish/buildx-alpine.Dockerfile
#    platforms:
#      - linux/amd64
#      - linux/arm64
#    tags:
#      - 'latest-alpine'
#      - '{{ .Tag }}-alpine'
#      - 'v{{ .Major }}.{{ .Minor }}-alpine'
#    labels:
#      # https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys
#      'org.opencontainers.image.title': '{{.ProjectName}}'
#      'org.opencontainers.image.description': 'Xdebug web'
#      'org.opencontainers.image.source': '{{.GitURL}}'
#      'org.opencontainers.image.url': '{{.GitURL}}'
#      'org.opencontainers.image.documentation': '{{.GitURL}}'
#      'org.opencontainers.image.created': '{{.Date}}'
#      'org.opencontainers.image.revision': '{{.FullCommit}}'
#      'org.opencontainers.image.version': '{{.Version}}'
